name: eva falls
favicon: null
layout_spectrum: 0
typography_spectrum: 0.38307
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4375
  lightness: 0.8156919188331813
  saturation: 0.9945249676238745
  rhythmicContrast: 0.4577722381800413
purpose: []
