name: eva falls
favicon: null
layout_spectrum: 0.24961
typography_spectrum: 0.38307
title: Straight Face Studios
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#707070'
    - '#3d3c3c'
    - '#a3a3a3'
    - '#fdfdfd'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.4577722381800413
purpose: []
